### ISSUE TITLE
Failed to build with rustc 1.35.0

### ISSUE THREAD

**Issue by yukinarit** [dalance/procs#18]
## Env

```bash
$ cat /etc/system-release
CentOS Linux release 7.4.1708 (Core)

$ rustc --version
rustc 1.35.0 (3c235d560 2019-05-20)
```

## Command

```bash
$ cargo install procs

   Compiling console v0.7.5
   Compiling procfs v0.5.2
   Compiling cookie v0.2.5
   Compiling structopt v0.2.17
   Compiling hyper v0.9.18
   Compiling palaver v0.2.1
error[E0308]: mismatched types
  --> /home/AD/yukinari.tani/.cargo/registry/src/github.com-1ecc6299db9ec823/palaver-0.2.1/src/valgrind.rs:15:39
   |
15 |     let err = unsafe { libc::getrlimit64(resource, &mut rlim) };
   |                                          ^^^^^^^^ expected u32, found i32

error[E0308]: mismatched types
  --> /home/AD/yukinari.tani/.cargo/registry/src/github.com-1ecc6299db9ec823/palaver-0.2.1/src/valgrind.rs:33:23
   |
33 |     let rlim = getrlimit(libc::RLIMIT_NOFILE).unwrap();
   |                          ^^^^^^^^^^^^^^^^^^^ expected i32, found u32

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `palaver`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `procs v0.8.5`, intermediate artifacts can be found at `/tmp/cargo-installot988m`

Caused by:
  build failed
```

**Comment by dalance** [comment]
Thanks. I send PR to palaver.
https://github.com/alecmocatta/palaver/pull/15

**Comment by dalance** [comment]
I changed the dependency crate from palaver to process_path because almost all function in palaver were not used.
I released v0.8.6 and it can be `cargo install`.

**Comment by yukinarit** [comment]
Success! Thank you!

```bash
$ cargo install procs

   Installed package `procs v0.8.6` (executable `procs`)
```
