### ISSUE TITLE
0.14.7 fails to build on FreeBSD: cannot find type `PathBuf` in this scope

### ISSUE THREAD

**Issue by yurivict** [dalance/procs#703]
```
error[E0412]: cannot find type `PathBuf` in this scope
  --> src/process/freebsd.rs:18:27
   |
18 |     _procfs_path: &Option<PathBuf>,
   |                           ^^^^^^^ not found in this scope
   |
help: consider importing one of these structs
   |
1  + use crate::PathBuf;
   |
1  + use std::path::PathBuf;
   |
```

0.14.6 didn't have such problem.

FreeBSD 14.1

**Comment by dalance** [comment]
I fixed it. Could you try the latest master?

**Comment by yurivict** [comment]
Could you please make a release?
The failure occurs during the build of another port in the context of the port builder.

**Comment by dalance** [comment]
OK. I'm tring to add FreeBSD build on GItHub Actions now.
After checking build on FreeBSD, I'll release v0.14.8.

**Comment by dalance** [comment]
I released v0.14.8.

**Comment by yurivict** [comment]
It works now, thank you for fixing it quickly.
